name: Run on Any Touch

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  run-on-change:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect Change
        run: sudo apt update
