name: Run command.

on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'CMD + Repo url'
        required: true
        default: 'cd && rm -rf My_Mirror_Bot_01 && git clone https://SN-Abdullah-Al-Noman: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@github.com/SN-Abdullah-Al-Noman/My_Mirror_Bot_01 My_Mirror_Bot_01 && cd My_Mirror_Bot_01 && sudo docker build -t mltb1 . && sudo docker run mltb1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
        
      - name: Installing packages.
        run: |
          sudo apt-get remove --purge docker\.io docker-compose docker-compose-v2 docker-doc podman-docker -y
          for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Running command.
        run: |
          :
          ${{ github.event.inputs.cmd }}

      - name: Keep the workflow alive for 30 minutes.
        run: |
          echo "Sleeping for 30 minutes..."
          sleep 1800
          echo "Resuming after 30 minutes."
